name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir build
        cargo install wasm-bindgen-cli wasm-pack
        wasm-pack build  --target web --out-dir build
        cp html/index.html build/
        
